import Layout from "@/components/Layout/Layout";
import Login from "@/components/Login/Login";
import SignUp from "@/components/SignUp/SignUp";
import {
  Code,
  Heading,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";

interface HomeProps {
}

const Home: React.FC<HomeProps> = ({ }) => {
  return (
    <Layout>
      <Head>
        <title>Awra Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack w="full" height="100vh" gap="3rem">
        <VStack pt="5rem">
          <Heading fontSize="7xl">Welcome to Awra</Heading>
          <Text>
            A secure chat app created to make Michael Shimeles feel like a great
            developer.
          </Text>
        </VStack>
        <VStack>
          <Tabs variant="line" colorScheme="blue" size="md">
            <TabList>
              <Tab>Sign Up</Tab>
              <Tab>Login</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <SignUp />
              </TabPanel>
              <TabPanel>
                <Login />
              </TabPanel>
            </TabPanels>
          </Tabs>
        </VStack>
      </VStack>
    </Layout>
  );
};

export default Home;

export const getServerSideProps = async (ctx: any) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx);
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  console.log("data", session);

  if (!session)
    return {
      props: {
        user: null,
      },
    };

  return {
    props: {
      initialSession: session,
      userServer: session.user,
    },
  };
};
